# Generated by Django 3.2.24 on 2024-02-29 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parse',
            old_name='certification',
            new_name='degree',
        ),
    ]
