# Generated by Django 3.2.24 on 2024-02-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_certification_parse_degree'),
    ]

    operations = [
        migrations.AddField(
            model_name='parse',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='parse',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parse',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parse',
            name='worked_as',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
    ]
