# Generated by Django 3.2.24 on 2024-02-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240229_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parse',
            name='email',
            field=models.EmailField(default='Not Specified', max_length=254),
        ),
    ]
