# Generated by Django 3.2.24 on 2024-02-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240229_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parse',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
